spring.application.name=backend
# Turn on the secret database website
spring.h2.console.enabled=true
# Give the database a specific name so we can find it
spring.datasource.url=jdbc:h2:mem:brainrotdb
# Default login credentials for our testing database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Tell Spring to automatically configure the H2 console for us
#spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Lock in the exact database name so it never changes
#spring.datasource.url=jdbc:h2:mem:brainrotdb
#spring.datasource.username=sa
#spring.datasource.password=
api.ninjas.key=Il0JHXinsz3jBNVsLfD6BH2nWbL3WKwd1J6nGABX
